name: Harvester Bot

on:
  push:
    branches:
      - harvester
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Fetch Git tags
      run: git fetch --tags

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: github-bot
        dockerfile: github-bot/Dockerfile
        tags: rancherlabs/harvester-github-bot:master
        build-args: |
          ARCH=amd64

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: github-bot
        dockerfile: github-bot/Dockerfile
        push: true
        tags: jk82421/harvester-github-bot:master
        build-args: |
          ARCH=amd64
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Install kubectl
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
        
    - name: Restart Deployment
      run: |
        kubectl rollout restart deployment -n github-bot github-bot --token=$TOKEN --server=$API_SERVER_ADDR --insecure-skip-tls-verify
      env:
        TOKEN: ${{ secrets.TOKEN }}
        API_SERVER_ADDR: ${{ secrets.API_SERVER_ADDR }}