name: Harvester Bot Pull Request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Fetch Git tags
      run: git fetch --tags
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: github-bot
        file: github-bot/Dockerfile
        push: false
        tags: rancherlabs/harvester-github-bot:${{ github.event.number }}
        build-args: |
          ARCH=amd64